// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMS.API.Data;

#nullable disable

namespace SRMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917043125_InitialEmergencyGreenWave")]
    partial class InitialEmergencyGreenWave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMS.API.Models.EmergencySession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid?>("SelectedRouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_route_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("SessionId");

                    b.HasIndex("SelectedRouteId");

                    b.ToTable("emergency_sessions");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadJunction", b =>
                {
                    b.Property<Guid>("JunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentSignalState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_signal_state");

                    b.Property<string>("JunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("junction_name");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("JunctionId");

                    b.ToTable("road_junctions");
                });

            modelBuilder.Entity("SRMS.API.Models.RouteJunction", b =>
                {
                    b.Property<Guid>("RouteJunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("route_junction_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("JunctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.HasKey("RouteJunctionId");

                    b.HasIndex("JunctionId");

                    b.HasIndex("RouteId", "JunctionId")
                        .IsUnique()
                        .HasDatabaseName("uq_route_junctions_route_junction");

                    b.ToTable("route_junctions");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalPreemptionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("JunctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("LogId");

                    b.HasIndex("JunctionId");

                    b.HasIndex("SessionId");

                    b.ToTable("signal_preemption_logs");
                });

            modelBuilder.Entity("SRMS.API.Models.TrafficRoute", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("route_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("distance_km");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_time_minutes");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route_name");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("start_location");

                    b.Property<string>("TrafficLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("traffic_level");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RouteId");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("SRMS.API.Models.EmergencySession", b =>
                {
                    b.HasOne("SRMS.API.Models.TrafficRoute", "SelectedRoute")
                        .WithMany("EmergencySessions")
                        .HasForeignKey("SelectedRouteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_emergency_sessions_selected_route_id");

                    b.Navigation("SelectedRoute");
                });

            modelBuilder.Entity("SRMS.API.Models.RouteJunction", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadJunction", "RoadJunction")
                        .WithMany("RouteJunctions")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_route_junctions_junction_id");

                    b.HasOne("SRMS.API.Models.TrafficRoute", "Route")
                        .WithMany("RouteJunctions")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_junctions_route_id");

                    b.Navigation("RoadJunction");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalPreemptionLog", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadJunction", "RoadJunction")
                        .WithMany("SignalPreemptionLogs")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signal_preemption_logs_junction_id");

                    b.HasOne("SRMS.API.Models.EmergencySession", "EmergencySession")
                        .WithMany("SignalPreemptionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signal_preemption_logs_session_id");

                    b.Navigation("EmergencySession");

                    b.Navigation("RoadJunction");
                });

            modelBuilder.Entity("SRMS.API.Models.EmergencySession", b =>
                {
                    b.Navigation("SignalPreemptionLogs");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadJunction", b =>
                {
                    b.Navigation("RouteJunctions");

                    b.Navigation("SignalPreemptionLogs");
                });

            modelBuilder.Entity("SRMS.API.Models.TrafficRoute", b =>
                {
                    b.Navigation("EmergencySessions");

                    b.Navigation("RouteJunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
