// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMS.API.Data;

#nullable disable

namespace SRMS.API.Migrations
{
    [DbContext(typeof(SrmsDbContext))]
    [Migration("20260918070139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMS.API.Models.AiWorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("approval_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DomainObjective")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("domain_objective");

                    b.Property<string>("ExecutionPlan")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_plan");

                    b.HasKey("Id");

                    b.ToTable("ai_workflow_executions", (string)null);
                });

            modelBuilder.Entity("SRMS.API.Models.JunctionCameraTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("telemetry_id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_id");

                    b.Property<string>("CongestionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("congestion_level");

                    b.Property<int>("DetectedVehicleCount")
                        .HasColumnType("integer")
                        .HasColumnName("detected_vehicle_count");

                    b.Property<Guid>("JunctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId", "RecordedAt");

                    b.ToTable("junction_camera_telemetry", (string)null);
                });

            modelBuilder.Entity("SRMS.API.Models.RoadJunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentSignalState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_signal_state");

                    b.Property<string>("JunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("junction_name");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("road_junctions", (string)null);
                });

            modelBuilder.Entity("SRMS.API.Models.SignalAdjustmentProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsApprovedByOperator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved_by_operator");

                    b.Property<Guid>("JunctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<int>("ProposedGreenExtensionSec")
                        .HasColumnType("integer")
                        .HasColumnName("proposed_green_extension_sec");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId", "IsApprovedByOperator");

                    b.ToTable("signal_adjustment_proposals", (string)null);
                });

            modelBuilder.Entity("SRMS.API.Models.JunctionCameraTelemetry", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadJunction", "Junction")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalAdjustmentProposal", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadJunction", "Junction")
                        .WithMany("Proposals")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadJunction", b =>
                {
                    b.Navigation("Proposals");

                    b.Navigation("TelemetryReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
