// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMS.API.Data;

#nullable disable

namespace SRMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926112127_AddWorkersAndWorkOrders")]
    partial class AddWorkersAndWorkOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMS.API.Models.AiWorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedCategory")
                        .HasColumnType("text");

                    b.Property<string>("DomainObjective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HazardReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputPayload")
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<long>("ProcessingMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("WasAutoVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AiWorkflowExecutions");
                });

            modelBuilder.Entity("SRMS.API.Models.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SRMS.API.Models.MunicipalWorker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("SRMS.API.Models.RepairWorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HazardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("HazardId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadHazardReport", b =>
                {
                    b.Property<Guid>("HazardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccelerometerZSpike")
                        .HasColumnType("numeric");

                    b.Property<string>("AiAnalysisSummary")
                        .HasColumnType("text");

                    b.Property<double>("AiConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AiDetectedCategory")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("integer");

                    b.HasKey("HazardId");

                    b.ToTable("RoadHazardReports");
                });

            modelBuilder.Entity("SRMS.API.Models.RepairWorkOrder", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadHazardReport", "Hazard")
                        .WithMany()
                        .HasForeignKey("HazardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRMS.API.Models.MunicipalWorker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hazard");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
