// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMS.API.Data;

#nullable disable

namespace SRMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924162901_AddAiWorkflowExecutions")]
    partial class AddAiWorkflowExecutions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMS.API.Models.AiWorkflowExecution", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("approval_status");

                    b.Property<string>("CompletedStepsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("completed_steps");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_stage");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_summary");

                    b.Property<bool>("HandoffReady")
                        .HasColumnType("boolean")
                        .HasColumnName("handoff_ready");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("objective");

                    b.Property<string>("ProposalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proposal_id");

                    b.Property<string>("ProposalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("proposal_status");

                    b.Property<string>("ProposedActionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("proposed_actions");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("thread_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ValidationNotesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_notes");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workflow_status");

                    b.HasKey("WorkflowId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_workflow_executions_session_id");

                    b.ToTable("ai_workflow_executions");
                });

            modelBuilder.Entity("SRMS.API.Models.EmergencySession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid?>("SelectedRouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_route_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("SessionId");

                    b.HasIndex("SelectedRouteId");

                    b.ToTable("emergency_sessions");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadJunction", b =>
                {
                    b.Property<Guid>("JunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentSignalState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_signal_state");

                    b.Property<string>("JunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("junction_name");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("JunctionId");

                    b.ToTable("road_junctions");

                    b.HasData(
                        new
                        {
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2071),
                            CurrentSignalState = "RED",
                            JunctionName = "Peradeniya Junction",
                            Latitude = 7.2580m,
                            Longitude = 80.5710m,
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2072)
                        },
                        new
                        {
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2077),
                            CurrentSignalState = "RED",
                            JunctionName = "Gatambe Junction",
                            Latitude = 7.2650m,
                            Longitude = 80.5780m,
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2078)
                        },
                        new
                        {
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2083),
                            CurrentSignalState = "GREEN",
                            JunctionName = "Hospital Junction",
                            Latitude = 7.2720m,
                            Longitude = 80.5850m,
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2083)
                        },
                        new
                        {
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2088),
                            CurrentSignalState = "RED",
                            JunctionName = "Town Junction",
                            Latitude = 7.2790m,
                            Longitude = 80.5920m,
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2088)
                        },
                        new
                        {
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2093),
                            CurrentSignalState = "RED",
                            JunctionName = "Lake Junction",
                            Latitude = 7.2860m,
                            Longitude = 80.5990m,
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 292, DateTimeKind.Utc).AddTicks(2093)
                        });
                });

            modelBuilder.Entity("SRMS.API.Models.RouteJunction", b =>
                {
                    b.Property<Guid>("RouteJunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("route_junction_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("JunctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.HasKey("RouteJunctionId");

                    b.HasIndex("JunctionId");

                    b.HasIndex("RouteId", "JunctionId")
                        .IsUnique()
                        .HasDatabaseName("uq_route_junctions_route_junction");

                    b.ToTable("route_junctions");

                    b.HasData(
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9877),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222201"),
                            SequenceNumber = 1
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9880),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222201"),
                            SequenceNumber = 2
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9883),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222201"),
                            SequenceNumber = 3
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333304"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9885),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222201"),
                            SequenceNumber = 4
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333305"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9888),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222202"),
                            SequenceNumber = 1
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333306"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9890),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111102"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222202"),
                            SequenceNumber = 2
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333307"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9892),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222202"),
                            SequenceNumber = 3
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333308"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9894),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111101"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222203"),
                            SequenceNumber = 1
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333309"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9897),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111103"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222203"),
                            SequenceNumber = 2
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333310"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9899),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111104"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222203"),
                            SequenceNumber = 3
                        },
                        new
                        {
                            RouteJunctionId = new Guid("33333333-3333-3333-3333-333333333311"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(9901),
                            JunctionId = new Guid("11111111-1111-1111-1111-111111111105"),
                            RouteId = new Guid("22222222-2222-2222-2222-222222222203"),
                            SequenceNumber = 4
                        });
                });

            modelBuilder.Entity("SRMS.API.Models.SignalPreemptionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("JunctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("junction_id");

                    b.Property<string>("PreviousSignalState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previous_signal_state");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("LogId");

                    b.HasIndex("JunctionId");

                    b.HasIndex("SessionId");

                    b.ToTable("signal_preemption_logs");
                });

            modelBuilder.Entity("SRMS.API.Models.TrafficRoute", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("route_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("distance_km");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_time_minutes");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route_name");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("start_location");

                    b.Property<string>("TrafficLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("traffic_level");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RouteId");

                    b.ToTable("routes");

                    b.HasData(
                        new
                        {
                            RouteId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(7212),
                            Destination = "Kandy",
                            DistanceKm = 5.00m,
                            EstimatedTimeMinutes = 15,
                            RouteName = "Route A",
                            StartLocation = "Peradeniya",
                            TrafficLevel = "HIGH",
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(7213)
                        },
                        new
                        {
                            RouteId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(7217),
                            Destination = "Kandy",
                            DistanceKm = 6.00m,
                            EstimatedTimeMinutes = 8,
                            RouteName = "Route B",
                            StartLocation = "Peradeniya",
                            TrafficLevel = "LOW",
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(7218)
                        },
                        new
                        {
                            RouteId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(7221),
                            Destination = "Kandy",
                            DistanceKm = 7.00m,
                            EstimatedTimeMinutes = 11,
                            RouteName = "Route C",
                            StartLocation = "Peradeniya",
                            TrafficLevel = "MEDIUM",
                            UpdatedAt = new DateTime(2026, 9, 24, 16, 29, 1, 291, DateTimeKind.Utc).AddTicks(7222)
                        });
                });

            modelBuilder.Entity("SRMS.API.Models.AiWorkflowExecution", b =>
                {
                    b.HasOne("SRMS.API.Models.EmergencySession", "EmergencySession")
                        .WithMany("AiWorkflowExecutions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_workflow_executions_session_id");

                    b.Navigation("EmergencySession");
                });

            modelBuilder.Entity("SRMS.API.Models.EmergencySession", b =>
                {
                    b.HasOne("SRMS.API.Models.TrafficRoute", "SelectedRoute")
                        .WithMany("EmergencySessions")
                        .HasForeignKey("SelectedRouteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_emergency_sessions_selected_route_id");

                    b.Navigation("SelectedRoute");
                });

            modelBuilder.Entity("SRMS.API.Models.RouteJunction", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadJunction", "RoadJunction")
                        .WithMany("RouteJunctions")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_route_junctions_junction_id");

                    b.HasOne("SRMS.API.Models.TrafficRoute", "Route")
                        .WithMany("RouteJunctions")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_junctions_route_id");

                    b.Navigation("RoadJunction");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalPreemptionLog", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadJunction", "RoadJunction")
                        .WithMany("SignalPreemptionLogs")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signal_preemption_logs_junction_id");

                    b.HasOne("SRMS.API.Models.EmergencySession", "EmergencySession")
                        .WithMany("SignalPreemptionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signal_preemption_logs_session_id");

                    b.Navigation("EmergencySession");

                    b.Navigation("RoadJunction");
                });

            modelBuilder.Entity("SRMS.API.Models.EmergencySession", b =>
                {
                    b.Navigation("AiWorkflowExecutions");

                    b.Navigation("SignalPreemptionLogs");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadJunction", b =>
                {
                    b.Navigation("RouteJunctions");

                    b.Navigation("SignalPreemptionLogs");
                });

            modelBuilder.Entity("SRMS.API.Models.TrafficRoute", b =>
                {
                    b.Navigation("EmergencySessions");

                    b.Navigation("RouteJunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
