// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMS.API.Data;

#nullable disable

namespace SRMS.API.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929072259_AddCrimeVehicleDetection")]
    partial class AddCrimeVehicleDetection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMS.API.Models.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SRMS.API.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fps")
                        .HasColumnType("integer");

                    b.Property<string>("LastPlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastScanTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScannedToday")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CameraId")
                        .IsUnique();

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CameraId = "CAM-101",
                            Fps = 60,
                            LastPlate = "",
                            LastScanTime = "Never",
                            Lat = 6.9271000000000003,
                            Lng = 79.861199999999997,
                            Name = "Main St & 5th Ave Intersection",
                            Resolution = "4K HDR ANPR",
                            ScannedToday = 0,
                            Status = "Active",
                            Zone = "Downtown Central"
                        });
                });

            modelBuilder.Entity("SRMS.API.Models.CctvNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CameraType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("CctvNodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CameraName = "Main Street CCTV",
                            CameraType = "LAPTOP_WEBCAM",
                            CreatedAt = "2026-01-01 00:00:00",
                            LastSeenAt = "Never",
                            Lat = 6.9271000000000003,
                            Lng = 79.861199999999997,
                            Location = "Main St & 5th Ave (University Simulated Node)",
                            NodeId = 1,
                            Status = "OFFLINE",
                            StreamSource = "LOCAL_WEBCAM",
                            StreamUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            CameraName = "University Gate CCTV",
                            CameraType = "MOBILE_CAMERA",
                            CreatedAt = "2026-01-01 00:00:00",
                            LastSeenAt = "Never",
                            Lat = 6.9175000000000004,
                            Lng = 79.882999999999996,
                            Location = "University Main Gate (University Simulated Node)",
                            NodeId = 2,
                            Status = "OFFLINE",
                            StreamSource = "PHONE_CAMERA",
                            StreamUrl = ""
                        });
                });

            modelBuilder.Entity("SRMS.API.Models.DetectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<bool>("CrimeMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHotlistMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<double>("OcrConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreatLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer");

                    b.Property<double>("VehicleConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.HasIndex("NodeId", "SessionId", "TrackId")
                        .IsUnique();

                    b.ToTable("DetectionLogs");
                });

            modelBuilder.Entity("SRMS.API.Models.DetectionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndedAt")
                        .HasColumnType("text");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("DetectionSessions");
                });

            modelBuilder.Entity("SRMS.API.Models.HazardAiWorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedCategory")
                        .HasColumnType("text");

                    b.Property<string>("DomainObjective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HazardReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputPayload")
                        .HasColumnType("text");

                    b.Property<string>("OutputPayload")
                        .HasColumnType("text");

                    b.Property<long>("ProcessingMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("WasAutoVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AiWorkflowExecutions");
                });

            modelBuilder.Entity("SRMS.API.Models.HotlistVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSeenCamera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MakeModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreatLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WantedSince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("SRMS.API.Models.MunicipalWorker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("SRMS.API.Models.PatrolUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DistanceToAlert")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadOfficer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("PatrolUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Callsign = "Patrol Alpha 4",
                            DistanceToAlert = "1.2 km",
                            Eta = "2 mins",
                            LeadOfficer = "Sgt. Miller & Off. Davis",
                            Sector = "Downtown Central",
                            Status = "AVAILABLE",
                            UnitId = "UNIT-402",
                            VehicleType = "High-Speed Interceptor Utility"
                        },
                        new
                        {
                            Id = 2,
                            Callsign = "Tactical Bravo 2",
                            DistanceToAlert = "2.8 km",
                            Eta = "4 mins",
                            LeadOfficer = "Capt. Reynolds (SWAT)",
                            Sector = "Financial District",
                            Status = "AVAILABLE",
                            UnitId = "UNIT-308",
                            VehicleType = "Armored Tactical Response Unit"
                        },
                        new
                        {
                            Id = 3,
                            Callsign = "Highway Patrol Delta 9",
                            DistanceToAlert = "4.5 km",
                            Eta = "6 mins",
                            LeadOfficer = "Off. Chen",
                            Sector = "Western Highway Corridor",
                            Status = "AVAILABLE",
                            UnitId = "UNIT-512",
                            VehicleType = "Dodge Pursuit Cruiser"
                        },
                        new
                        {
                            Id = 4,
                            Callsign = "Air Surveillance Recon 1",
                            DistanceToAlert = "0.8 km",
                            Eta = "1 min",
                            LeadOfficer = "Pilot Vance",
                            Sector = "City-Wide Aerial",
                            Status = "ON_PATROL",
                            UnitId = "UNIT-105",
                            VehicleType = "Eurocopter Emergency Drone/Chopper"
                        });
                });

            modelBuilder.Entity("SRMS.API.Models.RepairWorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HazardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("HazardId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("SRMS.API.Models.RoadHazardReport", b =>
                {
                    b.Property<Guid>("HazardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccelerometerZSpike")
                        .HasColumnType("numeric");

                    b.Property<string>("AiAnalysisSummary")
                        .HasColumnType("text");

                    b.Property<double>("AiConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AiDetectedCategory")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("integer");

                    b.HasKey("HazardId");

                    b.ToTable("RoadHazardReports");
                });

            modelBuilder.Entity("SRMS.API.Models.RepairWorkOrder", b =>
                {
                    b.HasOne("SRMS.API.Models.RoadHazardReport", "Hazard")
                        .WithMany()
                        .HasForeignKey("HazardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRMS.API.Models.MunicipalWorker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hazard");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
