using Microsoft.EntityFrameworkCore;

namespace SRMS.API.Data;

/// <summary>
/// Idempotent schema migration for pre-existing databases.
/// Database.EnsureCreated() only creates a database when it does not exist at all,
/// so existing smart_city databases need ALTER/CREATE statements applied manually.
/// All statements are safe to run repeatedly.
/// </summary>
public static class SchemaMigrator
{
    public static async Task RunAsync(AppDbContext db)
    {
        var now = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

        var statements = new[]
        {
            // --- DetectionLogs: multi-CCTV columns (existing rows get safe defaults) ---
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""NodeId"" integer NOT NULL DEFAULT 0;",
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""SessionId"" text NOT NULL DEFAULT '';",
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""TrackId"" integer NULL;",
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""VehicleType"" text NOT NULL DEFAULT '';",
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""VehicleConfidence"" double precision NOT NULL DEFAULT 0;",
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""OcrConfidence"" double precision NOT NULL DEFAULT 0;",
            @"ALTER TABLE ""DetectionLogs"" ADD COLUMN IF NOT EXISTS ""CrimeMatch"" boolean NOT NULL DEFAULT false;",

            // --- CCTV node registry ---
            @"CREATE TABLE IF NOT EXISTS ""CctvNodes"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""NodeId"" integer NOT NULL,
                ""CameraName"" text NOT NULL,
                ""Location"" text NOT NULL,
                ""CameraType"" text NOT NULL,
                ""Status"" text NOT NULL,
                ""StreamSource"" text NOT NULL,
                ""StreamUrl"" text NOT NULL DEFAULT '',
                ""CreatedAt"" text NOT NULL,
                ""LastSeenAt"" text NOT NULL
              );",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_CctvNodes_NodeId"" ON ""CctvNodes"" (""NodeId"");",

            // --- Mobile map: backend-provided node coordinates ---
            @"ALTER TABLE ""CctvNodes"" ADD COLUMN IF NOT EXISTS ""Lat"" double precision NULL;",
            @"ALTER TABLE ""CctvNodes"" ADD COLUMN IF NOT EXISTS ""Lng"" double precision NULL;",

            // --- Detection sessions (one per node monitoring run) ---
            @"CREATE TABLE IF NOT EXISTS ""DetectionSessions"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""SessionId"" text NOT NULL,
                ""NodeId"" integer NOT NULL,
                ""StartedAt"" text NOT NULL,
                ""EndedAt"" text NULL,
                ""Status"" text NOT NULL
              );",
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_DetectionSessions_SessionId"" ON ""DetectionSessions"" (""SessionId"");",

            // --- Duplicate protection: nodeId + sessionId + trackId must be unique ---
            @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_DetectionLogs_NodeId_SessionId_TrackId""
                ON ""DetectionLogs"" (""NodeId"", ""SessionId"", ""TrackId"");",

            // --- Seed node registry on databases created before nodes existed ---
            $@"INSERT INTO ""CctvNodes""
                (""NodeId"", ""CameraName"", ""Location"", ""CameraType"", ""Status"", ""StreamSource"", ""StreamUrl"", ""CreatedAt"", ""LastSeenAt"", ""Lat"", ""Lng"")
               SELECT 1, 'Main Street CCTV', 'Main St & 5th Ave (University Simulated Node)',
                      'LAPTOP_WEBCAM', 'OFFLINE', 'LOCAL_WEBCAM', '', '{now}', 'Never', 6.9271, 79.8612
               WHERE NOT EXISTS (SELECT 1 FROM ""CctvNodes"" WHERE ""NodeId"" = 1);",
            $@"INSERT INTO ""CctvNodes""
                (""NodeId"", ""CameraName"", ""Location"", ""CameraType"", ""Status"", ""StreamSource"", ""StreamUrl"", ""CreatedAt"", ""LastSeenAt"", ""Lat"", ""Lng"")
               SELECT 2, 'University Gate CCTV', 'University Main Gate (University Simulated Node)',
                      'MOBILE_CAMERA', 'OFFLINE', 'PHONE_CAMERA', '', '{now}', 'Never', 6.9175, 79.8830
               WHERE NOT EXISTS (SELECT 1 FROM ""CctvNodes"" WHERE ""NodeId"" = 2);",

            // --- Mobile map: backfill coordinates AFTER seed inserts (map markers need them) ---
            @"UPDATE ""CctvNodes"" SET ""Lat"" = 6.9271, ""Lng"" = 79.8612 WHERE ""NodeId"" = 1 AND ""Lat"" IS NULL;",
            @"UPDATE ""CctvNodes"" SET ""Lat"" = 6.9175, ""Lng"" = 79.8830 WHERE ""NodeId"" = 2 AND ""Lat"" IS NULL;",
        };

        foreach (var sql in statements)
        {
            await db.Database.ExecuteSqlRawAsync(sql);
        }
    }
}
