// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMS.API.Data;

#nullable disable

namespace SRMS.API.Migrations.SrmsDb
{
    [DbContext(typeof(SrmsDbContext))]
    [Migration("20261005090708_InitialSrmsDb")]
    partial class InitialSrmsDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("congestion")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMS.API.Models.AgentWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FinalOutcome")
                        .HasColumnType("text");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IntersectionId" }, "IX_AgentWorkflowRuns_IntersectionId");

                    b.HasIndex(new[] { "Status" }, "IX_AgentWorkflowRuns_Status");

                    b.ToTable("AgentWorkflowRuns", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.AgentWorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("text");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WorkflowRunId" }, "IX_AgentWorkflowSteps_WorkflowRunId");

                    b.ToTable("AgentWorkflowSteps", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.CameraSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LaneLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IntersectionId", "LaneLabel" }, "IX_CameraSensors_IntersectionId_LaneLabel")
                        .IsUnique();

                    b.ToTable("CameraSensors", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.Intersection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LaneCount")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Intersections", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.SensorFaultReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CameraSensorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CameraSensorId" }, "IX_SensorFaultReports_CameraSensorId");

                    b.HasIndex(new[] { "ReportedByUserId" }, "IX_SensorFaultReports_ReportedByUserId");

                    b.ToTable("SensorFaultReports", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalTimingDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DecidedByUserId" }, "IX_SignalTimingDecisions_DecidedByUserId");

                    b.HasIndex(new[] { "ProposalId" }, "IX_SignalTimingDecisions_ProposalId")
                        .IsUnique();

                    b.ToTable("SignalTimingDecisions", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalTimingProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafetyCheckNotes")
                        .HasColumnType("text");

                    b.Property<string>("SafetyCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IntersectionId" }, "IX_SignalTimingProposals_IntersectionId");

                    b.HasIndex(new[] { "WorkflowRunId" }, "IX_SignalTimingProposals_WorkflowRunId");

                    b.ToTable("SignalTimingProposals", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.TelemetryReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CameraSensorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid");

                    b.Property<double>("LaneDensityPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("QueueLength")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CameraSensorId" }, "IX_TelemetryReadings_CameraSensorId");

                    b.HasIndex(new[] { "IntersectionId", "Timestamp" }, "IX_TelemetryReadings_IntersectionId_Timestamp");

                    b.ToTable("TelemetryReadings", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", "congestion");
                });

            modelBuilder.Entity("SRMS.API.Models.AgentWorkflowRun", b =>
                {
                    b.HasOne("SRMS.API.Models.Intersection", "Intersection")
                        .WithMany("AgentWorkflowRuns")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("SRMS.API.Models.AgentWorkflowStep", b =>
                {
                    b.HasOne("SRMS.API.Models.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("AgentWorkflowSteps")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("SRMS.API.Models.CameraSensor", b =>
                {
                    b.HasOne("SRMS.API.Models.Intersection", "Intersection")
                        .WithMany("CameraSensors")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("SRMS.API.Models.SensorFaultReport", b =>
                {
                    b.HasOne("SRMS.API.Models.CameraSensor", "CameraSensor")
                        .WithMany("SensorFaultReports")
                        .HasForeignKey("CameraSensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRMS.API.Models.User", "ReportedByUser")
                        .WithMany("SensorFaultReports")
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CameraSensor");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalTimingDecision", b =>
                {
                    b.HasOne("SRMS.API.Models.User", "DecidedByUser")
                        .WithMany("SignalTimingDecisions")
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRMS.API.Models.SignalTimingProposal", "Proposal")
                        .WithOne("SignalTimingDecision")
                        .HasForeignKey("SRMS.API.Models.SignalTimingDecision", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalTimingProposal", b =>
                {
                    b.HasOne("SRMS.API.Models.Intersection", "Intersection")
                        .WithMany("SignalTimingProposals")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRMS.API.Models.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("SignalTimingProposals")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("SRMS.API.Models.TelemetryReading", b =>
                {
                    b.HasOne("SRMS.API.Models.CameraSensor", "CameraSensor")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("CameraSensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRMS.API.Models.Intersection", "Intersection")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CameraSensor");

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("SRMS.API.Models.AgentWorkflowRun", b =>
                {
                    b.Navigation("AgentWorkflowSteps");

                    b.Navigation("SignalTimingProposals");
                });

            modelBuilder.Entity("SRMS.API.Models.CameraSensor", b =>
                {
                    b.Navigation("SensorFaultReports");

                    b.Navigation("TelemetryReadings");
                });

            modelBuilder.Entity("SRMS.API.Models.Intersection", b =>
                {
                    b.Navigation("AgentWorkflowRuns");

                    b.Navigation("CameraSensors");

                    b.Navigation("SignalTimingProposals");

                    b.Navigation("TelemetryReadings");
                });

            modelBuilder.Entity("SRMS.API.Models.SignalTimingProposal", b =>
                {
                    b.Navigation("SignalTimingDecision");
                });

            modelBuilder.Entity("SRMS.API.Models.User", b =>
                {
                    b.Navigation("SensorFaultReports");

                    b.Navigation("SignalTimingDecisions");
                });
#pragma warning restore 612, 618
        }
    }
}
